### PR TITLE
refactor to use `Typography` components for text

### LINKED ISSUE #70: Create different text components
Like we talked about, we could wrap text into
```js
<TitleText/>
<SubtitleText/>
<BodyText/>
```

_Originally posted by @Phillip3 in https://github.com/echo-labs-team/the-resonance-project/pull/69_

### PR DESCRIPTION
**Pull request by dereckquock**
- fixes #70
- fixes [issues when user changes their system font size thru a11y](https://trello.com/c/ohc1r9Yz/135-fix-issues-when-users-change-their-default-text-size)

### CODE REVIEW

**Comment by Phillip3** [comment]
I’m assuming the ordering goes

Title
Subtitle
Heading
Text

?

**Comment by dereckquock** [comment]
> I’m assuming the ordering goes
> 
> Title
> Subtitle
> Heading
> Text
> 
> ?

i put it in the [README](https://github.com/echo-labs-team/the-resonance-project/pull/127/files#diff-2af5e1a31b17a1928347cc9959d8c058), but i should probably add a screenshot too

**Comment by Phillip3** [comment]
Hmm I read the readme and still didn’t get the ordering of major -> minor. Is it

Heading
Title
Subtitle
Text? 

Text comes first in the readme, so I’m not sure...

**Comment by dereckquock** [comment]
> Hmm I read the readme and still didn’t get the ordering of major -> minor. Is it
> 
> Heading
> Title
> Subtitle
> Text?
> 
> Text comes first in the readme, so I’m not sure...

`<Text>` is the base, then it goes Title -> Subtitle -> Heading
lemme make it more clear

**Review by Phillip3 — APPROVED** [review]
Woo! Love a good typography update. I really like this. We can refine it more as we go, but it's a beautiful start 💅

**Pull request merged**
